### ISSUE TITLE
可以加一个生成树状图的功能吗

### ISSUE THREAD

**Issue by 451222664** [CrazyFanFan/Aquarius#1]

**Comment by CrazyFanFan** [comment]
这个在计划中，我也在琢磨，依赖是个有向无环图，目前原生不太好做；短时间可能不会上线这个能力。

**Comment by lijianfeigeek** [comment]
@451222664 
cocoapods-graph 或许可以帮到，生成的是个环形图，依赖较多的情况下，好像不太容易看出来依赖关系。

**Comment by 451222664** [comment]
> @451222664
> cocoapods-graph 或许可以帮到，生成的是个环形图，依赖较多的情况下，好像不太容易看出来依赖关系。
谢谢，我现在用的就是 cocoapods-graph

**Comment by CrazyFanFan** [comment]
想要什么样的树，可以试试右键 =》 复制子节点(递归) ，会生成下面的效果，树大了会很慢
```
RxCocoa
├── RxRelay
│   └── RxSwift
└── RxSwift
```
