### ISSUE TITLE
依赖排序和影响排序

### ISSUE THREAD

**Issue by lijianfeigeek** [CrazyFanFan/Aquarius#2]
是否考虑增加依赖排序和影响排序？
目前看是按字母顺序排序的。

**Comment by CrazyFanFan** [comment]
可以具体描述下需求么？是指按照依赖数目和影响数目排序？

**Comment by lijianfeigeek** [comment]
是的，按照依赖数目和影响数目排序。
在做一些依赖库迁移的时候，可能会用到这一点。
首先迁移影响数目大的库，最后迁移依赖数目多的库。

**Comment by CrazyFanFan** [comment]
受限于目前的数据组织方式，排序不太好处理；
后续版本会加入此能力。

**Comment by lijianfeigeek** [comment]
我修改了源码，已经实现了哈~多谢了！

**Comment by CrazyFanFan** [comment]
最新的pre-release 已经支持排序，这里先关闭了；
https://github.com/CrazyFanFan/Aquarius/releases/tag/v3.0.0
