### ISSUE TITLE
项目运行失败

### ISSUE THREAD

**Issue by Archer353** [CrazyFanFan/Aquarius#7]
提示：”Missing package product 'Yams'“。我可以直接下载app使用，不过还是好奇这个问题怎么解决。

**Comment by CrazyFanFan** [comment]
可以试试更新最新的Xcode版本，我没遇到过依赖下载的问题，不是很确定是不是这个问题

**Comment by Archer353** [comment]
> 可以试试更新最新的Xcode版本，我没遇到过依赖下载的问题，不是很确定是不是这个问题

我这好了，猜测是Package.resolved文件格式有变化。解决方法：重新add package dependence，输入https://github.com/jpsim/Yams.git搜索添加时，会提示Package.resolved有损坏，删除后添加就可以了。

**Comment by CrazyFanFan** [comment]
应该是我用的xcode版本太新，resolved的version高导致的
